# Generated by Django 5.2.9 on 2025-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_question_test_delete_answer_delete_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'ordering': ['order', 'name'],
            },
        ),
    ]
