# Generated by Django 5.2.9 on 2025-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
        migrations.AddField(
            model_name='teammember',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Gmail'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram link'),
        ),
    ]
